ARG BASE_IMAGE
FROM $BASE_IMAGE

LABEL maintainer1="Stephan Lukasczyk <stephan@pynguin.eu>"
LABEL maintainer2="Benedikt Fein <fein@fim.uni-passau.de>"

RUN apt-get update \
    && apt-get install -y --no-install-recommends firefox-esr
