---
name: Build Container Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-base:
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: base
      subdir: base
  build-dejagnu:
    needs:
      - build-base
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: dejagnu
      subdir: dejagnu
  build-java:
    needs:
      - build-base
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: java
      subdir: java
  build-java-firefox:
    needs:
      - build-java
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: java-firefox
      subdir: java-firefox
      base_image: java
