---
name: Build Container Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-base:
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: base-ph2
      subdir: base
      build_args: |-
        MAVEN_VERSION=3.9.4
  build-dejagnu:
    needs:
      - build-base
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: dejagnu-ph2
      subdir: dejagnu
      build_args: ""
  build-java:
    needs:
      - build-base
    uses: ./.github/workflows/container-images.yml
    with:
      image_name: java-ph2
      subdir: java
      build_args: ""
